### ISSUE TITLE
Allow to use toReference method from outside, in ex. kn plugins

### ISSUE THREAD

**Issue by cardil** [knative/client#1202]
https://github.com/knative/client/blob/c503b88be21d859227d4e35471130e03c62def47/pkg/kn/commands/source/binding/binding.go#L77

Writing a kn-event plugin I wanted to parse the addressable in the same way as it is parsed in `kn source binding --subject` option. To be able to do it, this function needs to be moved to a public place. Maybe `knative.dev/client/pkg/util` is a good place?

**Comment by rhuss** [comment]
@cardil How urgent is it ? I'm asking because I'm on the way (albeit slowly) to move shared code into a dedicated repository to support reuse and break cyclic dependencies --> https://github.com/knative/client/issues/1039

It might still take a bit, but that will the eventual location where we should put the parsing code.

**Comment by cardil** [comment]
I wanted that to finish my kn-event poc. Either way this method needs to be public in order to enable reuse.

So, answering your question. I would like to do it as soon as possible. They I'm happy to follow up when the code gets transferred to other repo.
