### ISSUE TITLE
Why the documentation for the kn CLI not on the website?

### ISSUE THREAD

**Issue by csantanapr** [knative/client#1241]
This is the second time I get lost searching for the usage of a kn CLI command by going to the documentation site I can’t find it https://knative.dev/docs/

I think having this information on the site increases visibility and adoption 

 /kind question
 /kind doc

cc @omerbensaadon

**Comment by rhuss** [comment]
That's all my fault, it was planned since a [long time](https://github.com/knative/docs/issues/1555) and we started with some [automation](https://github.com/knative/client/issues/539) to add the doc extracted from the help messages but we never did the final step to auto-integrate this into the website.

There were more plans for additional docs as described in https://github.com/knative/client/issues/510#issue-525056785 but while super important, we are also very late (and understaffed).

Apologise, any suggestion on how to improve the situation would be helpful. I think as a first step we can continue to work on the automation. E.g what is missing currently is, that the website build process would pick up the markdowns that we generate [here](https://github.com/knative/client/tree/master/docs/cmd) . Here we could add the generated frontmatter, too.

**Comment by csantanapr** [comment]
I see a lot of activity on go code even more plugins created, what about pausing new features for a time period and focus on getting documentation automated and into the website I bet all folks contributing to CLI would not mind helping with docs for a short period

**Comment by csantanapr** [comment]
Docs should not be a one person (re understaff) open source will always be understaff :-) 
The same we can say about tests, the little staff on board needs to be decided into function, tests, and docs. 
this could be a good discussion for CLI WG to put foot down and say no more features are accepted until docs are in place

**Comment by csantanapr** [comment]
Is breaks my ❤️  so much innovation being done and no recognition or usage of the features no one will know about their existence. 

The same goes for a list of plugins available and how to installed them to be on the website and get visibility

**Comment by rhuss** [comment]
My feeling is if we have a simple foundation and automation (build integration) for the core document assets (reference manual, user manual, faq), then we can gather much more input and e.g. make it even an acceptance criterium when reviewing PRs.

However we need to get this automation rolling, which involves connecting the content-producing repo (this one) with the publishing-repo (website). I don't think we should host the CLI docs on the website repo as we then can't connect the content delivery with the code PRs that introduce new features.

**Comment by rhuss** [comment]
From the list of plugins tbh, there are only two in a ready to use status (admin & kafka source). There will be many more, and I totally agree without a central landing page, those plugins are lost. Also, we should think about a simple template for the plugin's documentation itself and introduce it to kn-plugin-sample, which is the blueprint for all new, golang based, plugins.

**Comment by csantanapr** [comment]
The automation the CLI folks could take a look is in the website git repo there is a script that copies files from docs and community into the website and then does the build. 
you could take same approach copy the md files from the client repo into website the same way docs and community content.

**Comment by csantanapr** [comment]
For the plugins today in the website I don’t know about the 2 that are ready

**Comment by csantanapr** [comment]
I think some of the foundation for the website is in place today because website repo is separated from docs repo that holds the content

where it gets tricky is the versioning the website only have 1 documentations version master/Head 0.20 0.19 ...

The script will pickup the CLI md files from a branch maybe the latest branch 0.20.x

But all this comes down to a simple bash script that exists today in website repo

**Comment by abrennan89** [comment]
@rhuss I'm going to go ahead and manually add CLI docs until we can figure out the automation part - I think it's better than nothing for now? woman_shrugging wdyt?

**Comment by rhuss** [comment]
yep, definitely ! Especially if we don't find some volunteer to work on this (i would like to help, but I'm totally overloaded right now :-(

thanks for taking care ...

**Comment by abrennan89** [comment]
Added a section to the docs site for CLI: https://knative.dev/development/client/

It's not complete since there will be a lot of additions in time, but I think CLI reference docs as a whole need to be built through completing smaller issues like https://github.com/knative/docs/issues/3496 and figuring out things like content reuse for adding all the reference docs for individual commands here, as well as where they're required as steps in a different procedural doc.

I'd prefer to close this issue @csantanapr and instead to add smaller issues for CLI commands as you notice them missing, since there's no way to really gauge when an issue this general / large is "complete"? There is an Epic for CLI docs that you can add issues to if you like: https://github.com/knative/docs/issues/3346

Thanks

**Comment by rhuss** [comment]
Sorry that this issue got lost in limbo. @abrennan89 @csantanapr how should we proceed ? 

Now that the website moves away from Hugo, I think that the automation needs to looks differently ? (or is there something similar like Hugo frontmatter for mkdocs ?)

**Comment by abrennan89** [comment]
@rhuss I recommend closing this issue and opening one specifically for automation that you can work on with @csantanapr and maybe @julz - I'm not sure how any of that would work for mkdocs

**Comment by abrennan89** [comment]
FYI there's an epic you can add kn doc issues to https://github.com/knative/docs/issues/3346

**Comment by rhuss** [comment]
Let's track the automation over there https://github.com/knative/docs/issues/4430 and close this issue (which will be fixed as soon as we have added this integration)
