### ISSUE TITLE
Consider `kn install` command to install serving and eventing components via `kn`

### ISSUE THREAD

**Issue by narenarjun** [knative/client#1281]
### Feature request
`kn` cli needs to have a `install` command which can be used to install `serving` component and `eventing` component separately or together respectively on a cluster.

### Use case

Every time i want to install the `knative` serving into the vanilla k8s cluster [not talking about openshift] , I have to look at the docs to get the install `yaml` or go to the knative serving github repo to download the a latest release yaml and apply it. This is time consuming and not super intuitive .

The idea behind this is `istio` have super sweet install command on their `istioctl` cli, which is snappier to install istio on the cluster and it comes with a set of profiles too which can be futher tweaked while installing. 

So, if `kn` have a install command such as  `kn install serve` and  `kn install event`  for serving and eventing respectively followed along with their own set of sub-command to tweak during install via passing flag or a value.yml file of some kind. 

/kind proposal

**Comment by zhanggbj** [comment]
The knative installation also takes my extra efforts and I've heard same concern from other folks.

Many CLI support installation. For e.g. the istioctl mentioned above, or the gloocli even support knative install like below

```
# glooctl install -h
choose which version of Gloo to install.

Usage:
  glooctl install [command]

Available Commands:
  knative     install Knative with Gloo on Kubernetes
```

Another proposal, perhaps we can add installation in the kn plugin [kn-admin](https://github.com/knative-sandbox/kn-plugin-admin) which target to take care of knative admin/ops work.

**Comment by rhuss** [comment]
There are several reasons why `kn` directly won't support any installation options for Knative itself

* The core `kn` CLI tool is targetting purely the developer persona for _using_ Knative
* `kn` can talk with the cluster only via the Knative API. It can not be assumed that Knative is always running on Kubernetes (there are other platforms than Kubernetes that are used for e.g. running CloudRun), so adding an `install` option is out of scope because you would need access to the cluster directly.

Said that, I definitely can see a place for a `knative-sandbox/kn-plugin-install` plugin for simple installs (used for development or demos), much like we have `kn-sandbox/kn-plugin-admin`. I wouldn't merge `install` and `admin` though as both serve different purposes.

**Comment by rhuss** [comment]
> Every time i want to install the `knative` serving into the vanilla k8s cluster [not talking about openshift] , ...

That's, because on OpenShift it should be just 2 or 3 clicks (or the creation of a simple `CluserServiceVersion` resource) to trigger a full install of OpenShift Serverless (aka Knative on OpenShift), and get updates automatically when released. Please ping me on slack or per mail (as this out of the scope of this issue), really interested in what makes it hard for you to install Knative on OpenShift) and hopefully we can fix that.

**Comment by csantanapr** [comment]
In the UX WG we did some user testing with one line command setup
Today we are using [konk](https://github.com/csantanapr/knative-kind)
We show them
![image](https://user-images.githubusercontent.com/1094878/115403018-01231f00-a1ba-11eb-86aa-e37060ccf535.png)

```
curl -sL install.konk.dev | bash
```
We got user feedback that it was not sure it wanted to curl website she was not aware

I think having a command like "kn install sandbox" or "know install kind" 
This will create a kind cluster, and install

That would install serving and/or eventing is a small start as we land into a general-purpose installer into an existing cluster and maybe do it when k8s ingress/gatewayv2 lands so we don't have to bother with the many options networking layers.

Maybe also it installs via the knative operator to avoid having so much logic in CLI/go code

istioctl and linkerd CLIs have an option for "install"

cc @omerbensaadon

**Comment by omerbensaadon** [comment]
+1 to the above comment!

Users like the 1-line install nature of konk, but the shell script makes people wary. One user even admitted that he's more comfortable using `brew` even though it functionally does the same thing.

**Comment by narenarjun** [comment]
> maybe do it when k8s ingress/gatewayv2 lands so we don't have to bother with the many options networking layers.
@csantanapr  so, if the k8s ingress/gateway matures enough will knative become free of the minimal service mesh layer it wants now for it's proper functioning ?

**Comment by csantanapr** [comment]
Yes @narenarjun when k8s gateway lands knative will support it and will not require a side ingress

**Comment by narenarjun** [comment]
>
> 
> Yes @narenarjun when k8s gateway lands knative will support it and will not require a side ingress

@csantanapr  wow, that's just awesome. When that comes,  Knative will make writing ingress route config go ancient , haha

**Comment by rhuss** [comment]
This is now tackled by the https://github.com/knative-sandbox/knative-plugin-quickstart repository, let's close it here.
