### ISSUE TITLE
[Proposal] Have `kn` look up plugins on `$PATH` by default

### ISSUE THREAD

**Issue by psschwei** [knative/client#1399]
### Feature request

The `kn` client by default will look in `$PATH` for plugins. This would mirror the performance of `kubectl` and provide an easier way for users to install plugins using tools like `brew`. 

### Use case

This arose out of discussions about the [quickstart plugin](https://github.com/knative-sandbox/kn-plugin-quickstart) we're building. The goal of that plugin was to provide a streamlined experience for new users to get up and running on Knative by running something like:

```bash
brew install knative/client/kn
brew install knative-sandbox/kn-plugins/quickstart
kn quickstart kind
```

However, the last command does not work, as `kn` by default does not look up plugins from `$PATH` (which is where `brew` installs them).

See also disucssion in [Slack](https://knative.slack.com/archives/CE4MVFVAQ/p1626964104136700) and in the [homebrew-kn-plugins repo](https://github.com/knative-sandbox/homebrew-kn-plugins/issues/23). 

/kind proposal
cc @omerbensaadon @csantanapr

**Comment by maximilien** [comment]
In principle I am not against this. As discussed in the [QuickStart PR](https://github.com/knative-sandbox/homebrew-kn-plugins/pull/24#issuecomment-885811128) I have added the link to show how this is how plugins worked initially for `kn`. 

However, as I recall, there was lots of discussions (which you can revive and re-read, if you want by searching plugin related issues and PRs) that resulted in where we are. So essentially this rehashes past decisions.

Since I've always been for look up in PATH as default --- simply because I wanted `kn` to behave like `kubectl` and I am pretty sure have mentioned this in these issues and PRs, I will recuse myself from this discussion until needed.

Good thing in all of this is that implementation to make `PATH` lookup default is a one liner + any test changes :) so hopefully decision is as quick. Cheers 🍻

**Comment by duglin** [comment]
+1 to this - I never liked that we didn't look in the PATH to being with :-)

**Comment by csantanapr** [comment]
+1 on looking in PATH like kubectl and oc plugins

**Comment by lance** [comment]
I like the idea of looking in `$PATH` for `func` because `func` can also be used standalone - i.e. not as a plugin - which is how I usually use it. If it's in my path then `func create` and `kn func create` are the same.

**Comment by rhuss** [comment]
> it's in my path then `func create` and `kn func create` are the same.

That's not true, it's still need to be called `kn-func`. So `kn-func` and `kn func` would be equivalent.

**Comment by rhuss** [comment]
I think we can allow a PATH lookup if we still can keep lookup from `~/.config/kn/plugins`.

My proposal would be:

* Lookup plugins from both, the path and `~/.config/kn/plugins`.
* Same named plugin in `~/.config/kn/plugins` take precedence over plugins found on the PATH.

This would also allow for system-wide plugins as installed by brew in `/usr/local/bin`, but allow individual users to override plugins in their `~/.config/kn/plugins` directory.

Also, for people that currently collect their plugins in `~/.config/kn/plugins` nothing would change. It's just as if you would add this directory to the front of your $PATH. I would then even _remove_ the config variable `lookupConfigInPath` as this would be always true then.

Actually, that was also my suggestion anyway when I proposed it at that time as a compromise for a discussion that was more heated then need to be :) --> https://github.com/knative/client/issues/269#issuecomment-512328613

**Comment by rhuss** [comment]
Decided in the WG Call: Let's go with this approach as this is the kubectl behaviour plus some own extension that could be used (or not) and allows user-specific plugins.
