### ISSUE TITLE
Change to Sugar Controller will impact inject Broker functionality option of "Kn trigger create"

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/client#1629]
Once https://github.com/knative/eventing/issues/5958 is addressed, Knative users will be able to configure the LabelSelector the Sugar reconciler will use to make injection decisions rather than the current behaviour which is static.

This will impact 
`--inject-broker      Create new broker with name default through common annotation`
option of `kn trigger create`

The LabelSelector will be populated in the sugar config file and would be the new source of truth.

**Comment by rhuss** [comment]
@xtreme-sameer-vohra thanks for the heads up. Somehow we overlooked the issue 😬 , but we plan to release a version 1.4.1 to deprecate `--inject-broker` on `kn trigger` and instead move this functionality to `kn admin` plugin for manipulating the corresponding config maps.

**Comment by xtreme-sameer-vohra** [comment]
Sounds good. Hoping the complete set of changes make it easier for users to automagically create Brokers for their Triggers.

**Comment by rhuss** [comment]
> Hoping the complete set of changes make it easier for users to automagically create Brokers for their Triggers.

well, it depends ;-) It's for sure more flexible, but it really needs support by a Knative admin to prepare the corresponding configuration, so that there is no assumption that the client can make (without reading that ConfigMap, but that is not allowed by `kn` as it strictly adheres to the Knative API contract, which does not support reading Knative implementation configuration).

So the only thing is that we can remove that option (which was convenient for users), and/or add the support for adding labels/annotations to `kn trigger`, but then the user would need to have the (hidden) knowledge which label/annotation to add (the one configured on the serving backend). I don't expect people to use the annotation then, but directly manage brokers with `kn broker`.

From UI perspective a more opinionated approach (without label selectors but with a fixed named label that is known by the client, aka as it is in serving <1.4) would have been better IMO.
