### ISSUE TITLE
Implement kn route delete command

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#204]
Just like `kn service delete`

**Comment by duglin** [comment]
Just wondering. Are we sure we want to expose all of the resources behind a KnService via the cli? It would be nice if we could push for all/most of the UX to be thru the service object to keep it simple. What are the use cases for needing to edits routes directly via kn instead of kubectl?

Thanks,
-Doug

**Comment by navidshaikh** [comment]
@duglin : 

> It would be nice if we could push for all/most of the UX to be thru the service object to keep it simple.

Why?
I don't see complexity in managing the other exposed objects via kn.

> What are the use cases for needing to edits routes directly via kn instead of kubectl?

I'd again ask, why?
Why we would like to intercept the scopes of client managing their respective API surfaces? As `kn` doesn't jump into k8s API surface, we should make `kn` scope to manage the resources exposed by knative APIs.

**Comment by duglin** [comment]
TBH I have mixed feeling on this topic. KnServing did a lot of work to move
towards a model where most everything should be done via the Service object
- thus hiding the Config and Routes from most people's view. And I think
that's great.  So, one part of me thinks we're doing the user a dis-service
(no pun intended) by now showing these resources to be on-par with
Service.  IOW, KnServing worked to try to hide them and now we're showing
them.

On the flip side... these resource ARE there and people may need to access
them.  But then I ask why? Under what cases would someone really need to
leave the scope of a KnService? If so, are those use cases enough of an
edge case that those folks would be using kubectl anyway?

To me kn is meant for people who don't want (or can't) deal with the
complex of kubectl and yaml - so a (sort of) even more opinionated model
than Knative itself.

And I should mention that I see value in at least being able to delete
Revisions because people need to clean up (what I expect will be a ton of)
revisions being created as they modify the KnService object.  But other
operations on Revisions seem questionable to me.

I'd be interested in hearing how other people feel? Is kn just a another
syntax for kubectl or is it meant to simply the model to some extent too?

**Comment by zhangtbj** [comment]
As a basic knative user, I think two same funtions/commands on both  knctl and kn cli may make me confusing. And I don't know which one is official or latest for knative.

I am not sure if kn cli can provide some more advantage functions than knctl to help end user manage or handle kn resources easily?

Such as show more useful and special knative info not just kube format style. Or cascade operation for convenience. Or complex operations to reduce user manual work.

**Comment by rhuss** [comment]
> As a basic knative user, I think two same functions/commands on both knctl and kn cli may make me confusing. And I don't know which one is official or latest for knative.

@zhangtbj do you refer to `kubectl` or `knctl` ?

One reason for having functionality duplicated in `kn` is that `kn` per-se *cannot assume that it operates agains a Kubernetes cluster*, because it is supposed to use only the Knative APIs. The reason for this is, that there are different implementation of Knative. Beside the Kubernetes one, there is e.g. Cloud Run on appengine which also use the Knative API but does not use Kubernetes under the hood.

So for such users, it makes not sense to use `kubectl` for deleting a route, but if they want to delete the route the would use `kn` as `kn` is the only client in use.

And although I share @duglin concerns to some degree, it's this use case of _managing Knative without an underlying Kubernetes_ which might be a motivation to add low level commands, too (although for Knative serving going only over the Service should be the 90% path).

**Comment by zhangtbj** [comment]
Got it, so should `kn` client support all knative serving/eventing and build resources CRUD?

Like the configuration of serving, should we also support its operation?

**Comment by rhuss** [comment]
> And I should mention that I see value in at least being able to delete Revisions because people need to clean up (what I expect will be a ton of) revisions being created as they modify the KnService object. But other operations on Revisions seem questionable to me.

With other operations you mean "showing" revisions (as 'update' is per definition not possible for a revision and 'create' is always done implicitely) ? If so, I'm definitely in favour to expose revision details over 'kn' to allow users to inspect the setup and status. This could happen through `kn service show` (maybe with some options to restrict on certain revision) or `kn revision show`, which I would prefer as it needs less options.

Back to this issue: I agree that we probably should not introduce a low-level `kn route delete` but make it easy to re-configure the service so that the route gets delete here. Route create/update/delete should happen IMO always by changing the configuration of  a service only, never directly. (BTW, I'm not sure what would happen if one deletes a route that is currently referenced by a service. Does it get recreate automatically ?)

**Comment by rhuss** [comment]
> Got it, so should `kn` client support all knative serving/eventing and build resources CRUD?

For serving we should do all write operations through changing the Service IMO. Read operations (list, show) can be on other finer granular entities, too (routes, revisions).

**Comment by zhangtbj** [comment]
Interesting, I tried to delete a route and I found it is recreated automatically:
```
jordanzt@zhangtaodembp:~/Works/workspaces/gopath/src/github.com/knative/client$ kubectl delete route picalc
route.serving.knative.dev "picalc" deleted
jordanzt@zhangtaodembp:~/Works/workspaces/gopath/src/github.com/knative/client$ kubectl get routes
NAME                       URL                                                                                       READY     REASON
helloworld                 http://helloworld-default.kubecon2019.us-south.containers.appdomain.cloud                 True
picalc                     http://picalc-default.kubecon2019.us-south.containers.appdomain.cloud                     True
```

And I agree `all write operations through changing the Service`. For read operations, beside routes, revisions, does kn client need `configuration`?

**Comment by rhuss** [comment]
No, Configuration is totally opaque imo. Everything you can read from a configuration can be seen in a service, too.

**Comment by navidshaikh** [comment]
Routes to be managed fully via service.
