### ISSUE TITLE
Support v1beta1 (alongside v1alpha1)

### ISSUE THREAD

**Issue by sixolet** [knative/client#260]
## Describe the feature:

Right now we support v1alpha1. In preparation for v1beta1, we may want to support both API versions simultaneously, picking between with a flag.

This would require refactoring KnClient to return union types of the two API types, and the union type would have to implement all the relevant getters and setters. At least, that's one way of doing it.

**Comment by zhangtbj** [comment]
Hi @sixolet ,

Should we add a global flag in kn client to set the api version globally?

Such as:
```
Usage:
  kn [command]

Available Commands:
...

Flags:
      --apiversion string       Knative api version (default is v1alpha1)
```

Then provide a upper level common new `NewKnServingClient` in knClient to init the client by using the different api version.

**Comment by rhuss** [comment]
I also thought about an autodetection mechanism to automatically pickup whatever the server prefers (by inspecting the CRD this should be possible). However not sure whether inspecting the CRD is in scope of the KnApi, so having an overrule might be useful, too.

@zhangtbj Since I did the refactoring of KnClient I already have some rough ideas how to proceed to support multiple version. It's not so easy as it sounds. Therefore I would like to work on this issue, too, but happy to collaborate on this. Would this be fine for you ?

**Comment by rhuss** [comment]
> This would require refactoring KnClient to return union types of the two API types, and the union type would have to implement all the relevant getters and setters. At least, that's one way of doing it.

It will be interesting how we could get bring such a union type together with the printers from cli-runtime . I'm not sure which characteristics such types would need to have.

Tbh, I'm a bit afraid to duplicate too much the Knative serving objects.

So another idea was, that we might as equally stick to the highest possible API version for the exposed data objects (like v1beta1.Service for now) and do an internal conversion in the interface's implementation to lower api versions if required (e.g. when the cluster only supports v1alpha1).

For future versions (e.g. v1beta2), this would mean that users of this interface need to decide whether they want to upgrade the dependency on `knative/client` and update their code to deal with `v1beta2` or stick to the old dependency on `v1beta1`.

@sixolet wdyt ?

**Comment by zhangtbj** [comment]
hi @rhuss,

Sure thing. I can aslo help if there are some subtasks here.

I think auto-check is a good way, so that end user doesn't need care about that.

Then in kn client side, we can detect and choose and return the correct version.

And about the printers. Are there many changes between different version? Such as 
v1alpha1 to v1beta2. I think knative should consider compatibility.

**Comment by rhuss** [comment]
We can close this, as we switched already to v1. We decided to stick a single version in the `kn` client for accessing a single endpoint, and align this with the serving lifecycle (e.g. as serving is dropping v1alpha1 support in 0.13.0, so we do in 0.13.0, too)
