### ISSUE TITLE
Kn plugins should have configurable prefix

### ISSUE THREAD

**Issue by maximilien** [knative/client#288]
## In what area(s)?

Kn plugins

/kind feature
/kind proposal

## Describe the feature:

Currently Kn plugins (when PR #249 is merged) requires that plugins are named with `kn` prefix. So for a list of plugins:

```bash
➜  client git:(kn-plugins4) ./kn --lookup-plugins-in-path=true plugin list
Using kn config file: /Users/maximilien/.kn/config.yaml
The following compatible plugins are available, using options:
  - plugins dir: '~/.kn/plugins'
  - lookup plugins in path: 'true'

/Users/maximilien/.kn/plugins/kn-hello
/usr/local/bin/kn-foo-bar
/usr/local/bin/kn-foo_bar
/usr/local/bin/kn-hello
  - warning: /usr/local/bin/kn-hello is overshadowed by a similarly named plugin: /Users/maximilien/.kn/plugins/kn-hello
/usr/local/bin/kn-kn
/usr/local/bin/kn-knctl

error: one plugin warning was foun
```

All the plugins files have `kn-` as a prefix.

It would be valuable to allow plugins to have either no prefixes when in the `--plugins-dir` or a different prefix, e.g., `google` or `ibm`. We could achieve this by having a configurable `--kn-plugins-prefixes` flag. So listing plugins would be something like:

```bash
➜  client git:(kn-plugins4) ./kn --no-kn-plugins-prefix plugin list
Using kn config file: /Users/maximilien/.kn/config.yaml
The following compatible plugins are available, using options:
  - plugins dir: '~/.kn/plugins'
  - lookup plugins in path: 'true'

/Users/maximilien/.kn/plugins/hello
```

and

```bash
➜  client git:(kn-plugins4) ./kn --lookup-plugins-in-path=true --kn-plugins-prefixes=kn,ibm plugin list
Using kn config file: /Users/maximilien/.kn/config.yaml
The following compatible plugins are available, using options:
  - plugins dir: '~/.kn/plugins'
  - lookup plugins in path: 'true'

/Users/maximilien/.kn/plugins/kn-hello
/usr/local/bin/kn-foo-bar
/usr/local/bin/ibm-foo-bar
```

Initially suggested by @sixolet

**Comment by rhuss** [comment]
Tbh I don't see the value of this feature. I really would like to establish 1 single fixed prefix when running outside a plugin directory(which imo should also not be configurable), so that people immediately can identify a kn plugin when they see it. I would also insist on this prefix when having it in ~/.kn/plugins so that plugins can be easily moved around.

What I also still not get that these plugin options (`--lookup-plugins-in-path`, `--plugin-dir` (if so)) needs to be options and can't be pure configuration values, because:

* It's a setup thing, no need to provide this option for *every single call* to kn if you decide for your personal plugin setup. No one will do that.
* It's a global option which pollutes every help message. 

Same reason goes to for not showing this configuration setup on `kn plugin list`, as its a constant value and distracts from the actual requested information, the plugins available. Maybe we can hide this behind a `--verbose` option or make it part of a `kn config view` ?

The simpler the better.

**Comment by maximilien** [comment]
Relatively easy to change. Agree that these options could be loaded from config, though that also begs the question of what those options in config are and how to easily change. Perhaps when #259 is set and a way to modify them, e.g., `kn config set/unset ...` or similar should make things easier.

**Comment by maximilien** [comment]
Closing this. No one is asking for it. The prefix `kn-` is good enough.

We can always reconsider this if users ask for it.
