### ISSUE TITLE
Add `--dry-run` option to service create and update operations

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#293]
> /kind feature
> /kind proposal

## Describe the feature:

```
--dry-run=false: If true, only print the object that would be sent, without sending it.
```

flag can be added in `service create`, `service update` and traffic splitting commands (if we chose to have new verbs for them).

**Comment by maximilien** [comment]
I like this a lot... might not be easy but should force us to separate setup, action, and cleanup for each command. Perhaps the mock stuff that #306 is introducing could help in this?

**Comment by rhuss** [comment]
I'm happy with this feature but I probably wouldn't call it `dry-run`, as this typically means to have the normal output but with no state change (i.e. not a different kind of output).

Wdyt about an `--export` or  `-o yaml` option, which means that you could save the output e.g. for gitops operation ? (but also for debugging purposes).

In addition, and in the spirit of #333 we could add a debug category "resources" so that a `--debug=resources` would also print out those objects but actually would also perform the action on the server-side.

**Comment by maximilien** [comment]
@rhuss I think what you are suggesting is valid and valuable but I see the `--dry-run` as not overlapping fully and useful for the end user human operator / developer wanting to check their command(s) before actually doing it! So I would keep this issue and just add another or update the current #30

**Comment by danielhelfand** [comment]
Anyone working on this? Would like to pick this up as it would be helpful to have for our work around gitops/CICD.

**Comment by navidshaikh** [comment]
/remove-lifecycle stale

@danielhelfand are you still looking at it? @itsmurugappan wanted to work on this.

**Comment by danielhelfand** [comment]
/unassign

Sure, please feel free to pick it up.

**Comment by rhuss** [comment]
I think we kind of implemented it with the `--target` option. So let's close this issue.
