### ISSUE TITLE
Traffic splitting design: separate verb vs. part of `service update`

### ISSUE THREAD

**Issue by sixolet** [knative/client#295]
One of several polls about how our traffic splitting and tagging should be set up. This is about whether we want a **separate command** for traffic splitting/tagging, or have it be **part of service update**, for the MVP only.

**Comment by sixolet** [comment]
Traffic splitting should be a **separate command** for the MVP, like `kn service set-traffic foo ...`

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
Traffic splitting should be **part of service update** for the MVP, like `kn service update foo --traffic ...`

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
... Further discussion below. As for my feelings: The separate command option helps keep `service update` focused on changing the revision template, and helps keep the number of `service update` options manageable. On the other hand, it technically *is* a service update.

**Comment by duglin** [comment]
Yup - it is just a service update and see my comment here: https://github.com/knative/client/issues/296#issuecomment-514855015  It will increase the # of `kn` commands people have to do when compared to `kubectl`. I think this will be very important when people want to update their service and have a new traffic split available immediately w/o any gap where the traffic split is old - sort of an atomic operation like they get with kubectl.

**Comment by navidshaikh** [comment]
Separate commands for setting traffic targets and their tags, not only helps,
- keeping service update focused on changing the revision template
- keeping service update options manageable

but also helps,

- defining clear paths to manage objects encapsulated by Service spec, ConfigurationSpec [`service create`, `service update`] , RouteSpec [`service tag-targets`, `service set-traffic`]
- users to have their revisions ready/desired-state before actually starting to route traffic to them
- have clear distinction between `update` and `set`, for `service update` we don't change what isn't mentioned, while for `service set-traffic` what's specified on the CLI replaces the existing traffic block
- separate commands and their outcome, `service update` would yield a new revision while `service set-target` won't

Trading this distinction with be-able-to-specify all in one `service update` commands brings complexity and might add confusion, because if we don't want separate commands, then we need to also have `tags` manipulation in `service update` itself using the trio of `revisionName:percent:tag` among which all are optional fields to fit use-cases, imagine number of combinations it'd generate.

**Comment by duglin** [comment]
> defining clear paths to manage objects encapsulated by Service spec

I actually think this is reason NOT to split them. We should not be dealing with anything but Service - if we can.  Implying that there's complexity with dealing with just Service implies the server side made a mistake by trying to have a single object on which people act. I don't think it was a mistake.

**Comment by rhuss** [comment]
> I actually think this is reason NOT to split them.

It's not about splitting (they are all part of `kn service`) but separating them on the sub-command level a much as Knative servicing separates those concerns top-level within the `spec:` on the server-side.

**Comment by duglin** [comment]
I view this as putting the choice in the user's hands.  If they think it's confusing to have one longer command that does it all at once, then they can split the commands into multiple steps. 

`kn service myapp set-traffic foo ...`  
vs
`kn service myapp update -t foo ...` 

it's not much of a diff, but gives the user more freedom to do the steps in the order and size that makes sense to them.
