### ISSUE TITLE
Traffic splitting design: tags with percents vs. tags separate from percents

### ISSUE THREAD

**Issue by sixolet** [knative/client#296]
One of several polls about how our traffic splitting and tagging should be set up. This is about whether we want to put percents and tags for revisions into the same syntax for setting up a traffic section, or different separate syntaxes.

**Comment by sixolet** [comment]
Traffic splitting should use a **combined syntax** for specifying revisions, tags, and percents, like `foo-asdf:100:current` (revision:percent:tag)

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
Traffic splitting should use a **separate syntax** for specifying revisions/tags and percents vs. revisions and tags, like `foo-asdf:100` for percents, and `foo-asdf:current` for tags. The percent syntax can also accept a tag in place of a revision name, like `current:100`.

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
... Further discussion below.

**Comment by duglin** [comment]
I don't necessarily see it as an either-or choice.

I think when you're updating an existing traffic block we might be able to do it via a xxx:yyy (similar to what @rhuss mentioned in https://github.com/knative/client/pull/285#discussion_r306648112 - I'm still working thru it, but it looks interesting).

However, when you're defining a new traffic block I would find it annoying to have to do two commands because I can't specify both a tag and a revisionName at the same time as the percentage.
For example, I have a demo where in the last step of setting up the service I do a kubectl with this traffic block:
```
  traffic:
  - tag: helloworld-v1
    percent: 50
    revisionName: helloworld-v1
  - tag: helloworld-v2
    percent: 50
    revisionName: helloworld-v2
  - tag: helloworld-test
    latestRevision: true
    percent: 0
```
and I do this by defining the helloworld-v2 revision and this entire traffic block all with one kubectl command. I'm not sure how many it would take if we only supported the separate syntax but I'm sure it would be more than one - and it would require a mental mapping by the user across the commands.

What I'm trying to say is that I think we could actually do both.
