### ISSUE TITLE
Traffic splitting design: service surface vs revision surface.

### ISSUE THREAD

**Issue by sixolet** [knative/client#297]
One of several polls about how our traffic splitting and tagging should be set up. This one is about whether traffic splits should be under `service` or `revision`.

**Comment by sixolet** [comment]
`service`

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
`revision`

Vote for this by giving this comment a 👍

**Comment by sixolet** [comment]
... Further discussion below.

**Comment by duglin** [comment]
I voted for service because that's supposed to be the main entrypoint for users. It's the reason the traffic block exists on Service. Plus having `kn` operate on Service aligns it with what people will do via `kubectl`, which is operate on the Service, and I think that consistency is important if they ever need to do something that `kn` doesn't support.

**Comment by navidshaikh** [comment]
The revision entry point was initially proposed for tagging operations only, voted for `service` entry point as it suits better there and to align better with `set-traffic` verb.
