### ISSUE TITLE
have `kn service list` show latest revision name

### ISSUE THREAD

**Issue by duglin** [knative/client#360]
/kind good-first-issue
/kind feature
/kind proposal

## Describe the feature:

Today `kn service list` will show:
```
NAME   URL                                                             GENERATION   AGE   CONDITIONS   READY   REASON
echo   http://echo-default.kndev.us-south.containers.appdomain.cloud   2            65s   3 OK / 3     True    
```

Notice the revision name is not there. Seeing the revision name is important for users so they can know when the latest version of their app has been deployed and ready to be hit.

See similar output from `kubectl get ksvc`:
```
NAME   URL                                                             LATESTCREATED   LATESTREADY   READY   REASON
echo   http://echo-default.kndev.us-south.containers.appdomain.cloud   echo-v1         echo-v1       True    
```

Proposal: add a `Latest Revision` or just `RevisionName` column so people can see which is the latest revision that's going to be used.

I'd drop `Generation` as that's a number that's not very useful for end-users, other than to know it's been changed, which is only true if they're tracking it. Someone like that, I suspect, would probably be naming their revisions and would be more interested in seeing this new column's value instead.

Not sure I see value in `Conditions` either since seeing `0/3` or `3/3` doesn't really give any more useful info than the overall `Ready` column - I'd drop it too.

**Comment by navidshaikh** [comment]
About Generation column, I agree I don't find it useful too.

> Seeing the revision name is important for users so they can know when the latest version of their app has been deployed and ready to be hit.

IMO if we're after revision's status here, so the command should be `kn revision list -s service`,
as it could also show me the reason for it if revision didnt come up or progressing.

While working on traffic splitting, I found that I'd want to list the current state of service's revision ordered by their generation and showing if they are ready, this was the motivation to sort the revisions based on the generation with new generation column https://github.com/knative/client/issues/289. I think that should be the way to go for the use case you mentioned, even better if user is very keen, he might

```
watch kn revision list -s service 
```

and see all the conditions passing one by one.

About the conditions and revision column, I agree. We could do better there, for example in default output, when all services are ready, don't show up the conditions and reason column at all.
Those two columns are added at the end, if any of the service isn't ready yet.

So we could keep the service list columns even more compact (adjusting for long URLs users might have, as you have in paste) only listing `NAME,URL,READY`. I don't find AGE column useful either. 
One of the column could be kept reserved for something which might integrate with knative service, for eg eventing, since we might want to keep it close to service listing to indicate that, OR something else..

**Comment by navidshaikh** [comment]
`kn revision list -s service` should show latest revision created for the service.
Beside, I think we need to revisit the information we show in service, revision, route list commands and have them output only most relevant information.
