### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#444]
Release cadence for knative/client needs to be improved. Logging the issue to track and discuss.

The last release v0.2.0 for client happened on Jul 11. There are issues filed complaining x not 
working on released version, but fixed on master.

What are suggestions on streamlining the release process?

We can look at
1 - Documenting the release process
2 - ~3~ 6 weeks release cadence
3 - Having milestones tagged with due dates at the time of creation
4 - 3 milestones available
5 - Assign maintainer round robin per release

**Comment by rhuss** [comment]
👍 I think a fixed cadence is more important than sticking to a planned feature set. E.g. I think we already have tons of more feature over 0.2.0 that would make a 0.8.0 valuable even when not all features tagged with a 0.8.0 milestones are implemented yet.

**Comment by rhuss** [comment]
We could align the cadence with serving & eventing that we have the same length for the release cycle but do the release _one week after_ serving/eventing releases, so that there is a window to adapt to the latest changes on these dependent projects. I guess the serving/eventing operators or any other project which depends on serving/eventing has a similar timing issue.

**Comment by maximilien** [comment]
+1 for a more frequent and regular release schedule.

**Comment by navidshaikh** [comment]
Release process documented at https://github.com/knative/test-infra/blob/master/ci/release_setup.md#setting-up-automated-releases

**Comment by rhuss** [comment]
I think we can close this issue as our new 6-week release cadence seems to be stable.
