### ISSUE TITLE
Is BASH completion needed and useful?

### ISSUE THREAD

**Issue by maximilien** [knative/client#456]
## In what area(s)?

`completion` command

Classifications:

> /kind usage

## Ask your question here:

We added `zsh` completion but it was useless so it's removed in #439 and @rhuss raised the [question](https://github.com/knative/client/pull/439#issuecomment-540977753) if we should also remove BASH completion since it's not also too useful.

Separating the two concerns with this issue. We can discuss BASH completion's merits or lack of here and allow #439 to be merged independently.

**Comment by maximilien** [comment]
@sixolet any opinion on this?

**Comment by rhuss** [comment]
My feeling is, that completion is useful if we would also add context-sensitive information (like completing on actual service/revision names for e.g. `kn service describe`). The icing on the cake would be to over e.g. tag names for completion when doing a `kn service update --traffic <tab>`.

Having only the auto-generated completed is a nice add-on if it works (and it doesn't for zsh completion as it breaks when a help message contains a `[` because it then generates invalid shell scripts). We could restrict ourselves to bash-completion, but for now, I think the maintenance costs outweigh the benefits.

**Comment by navidshaikh** [comment]
We have the spf13/cobra dep update merged with zsh completion fix, I'll add back the zsh completion.
