### ISSUE TITLE
Sample source plugin

### ISSUE THREAD

**Issue by rhuss** [knative/client#520]
A sample source plugin should be created in parallel to #519 to validate the implementation.

Ideally, the plugin is for an already source like one of those from https://github.com/knative/eventing-contrib

To also provide some value, I'd suggest using the [KafkaSource](https://github.com/knative/eventing-contrib/tree/master/kafka) or [GitHubSource](https://github.com/knative/eventing-contrib/tree/master/github) as a sample.

**Comment by rhuss** [comment]
I suggest to use the KafkaSource as first plugin as it looks like that there is some demand for this and its probably also the most useful source (outside of demos).

**Comment by maximilien** [comment]
Hey @rhuss I discussed with @daisy-ycguo and she’ll be doing the Kafka plugin as I am already doing the GitHub one. The good thing with this split is that by the time we are done we will have both and also some common code. 

This is actually a great side effect since I really want to have common code for source plugins in single place to avoid repetition.

That said, might make sense to create a specific issue for @daisy-ycguo on the Kafka plugins and assign to her. Thanks.

**Comment by navidshaikh** [comment]
Kafka source plugin https://github.com/knative/client-contrib/pull/19

**Comment by maximilien** [comment]
We are moving these (all plugins) to knative-sandbox and https://github.com/knative-sandbox/kn-plugin-source-kafka is already there though is being updated. I think we can close this issue.
Cc: @daisy-ycguo

**Comment by rhuss** [comment]
I think it would still be helpful to have an example for a source plugin. Maybe we can create a `knative-sandbox/kn-plugin-samples` that could hold multiple samples for plugins (for "hello-world", for sources, ...). or we could also have multiple repositories in the sandbox, one for each sample.

wdyt ?

**Comment by rhuss** [comment]
I still think this is would be a valuable addition, so I move the issue over to sandbox and the sample plugin, as I think it would make sense to have the sample plugin possibly within the same repository.

**Comment by rhuss** [comment]
Closing this one here, let's followup with the issue over there in the sandbox
