### ISSUE TITLE
Add E2E tests for CronJob source

### ISSUE THREAD

**Issue by rhuss** [knative/client#566]
similar to for E2E tests for ApiServer source. Ideally this should involve also a service to connect to and checking whether cronjob events have been delivered.

- [x] Add CronJob create/update/delete tests
- [ ] Verify the events at configured sink

**Comment by MIBc** [comment]
I'd like to try.

**Comment by navidshaikh** [comment]
/reopen

(for verifying the events at the sink)

**Comment by daisy-ycguo** [comment]
> /reopen
> 
> (for verifying the events at the sink)

@navidshaikh will you provide more details for "verifying the events at the sink" ?

**Comment by navidshaikh** [comment]
@daisy-ycguo : We can use `gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display` to receive events and verify events from logs.

**Comment by daisy-ycguo** [comment]
I will take care of the item: `Verify the events at configured sink`.

**Comment by daisy-ycguo** [comment]
@rhuss @navidshaikh 
I don't think we should work on this test case `Verify the events at configured sink`. It should be a part of e2e test of eventing. We could `verify that pingsource could be described correctly`. Because if pingsource could be described correctly, and eventing functions work well, it's definitely true that event message could be sent to sink.

The reason that I question this requirement is that I'm not able to implement this test case based on the GKE with Istio add-on testing environment. Eventing has the [pingsource e2e test case](https://github.com/knative/eventing/blob/master/test/e2e/source_ping_test.go) working well with [`--skip-istio-addon` enabled](https://github.com/knative/eventing/blob/master/test/e2e-tests.sh#L31) in their test environment. While if we disable istio add-on, some serving test cases might be failed according to @chizhg 's [comment](https://github.com/knative/test-infra/issues/1784#issuecomment-595439342).

So I recommend to change the test case to `verify pingsource description`.

**Comment by rhuss** [comment]
Sounds reasonable, but I really wonder how eventing the e2e tests pingsource if it doesn't work with the setup given ?
