### ISSUE TITLE
e2e test fails if there are resouces created by the previous test

### ISSUE THREAD

**Issue by MIBc** [knative/client#576]
## Describe the feature:

The e2e test may fail in sometime, for example failing download docker image.  When start test again, it will fail for some existed resource. In this situation, I have to clear resource manually.
Is there a command or shell to clear all resource the test has created?

**Comment by rhuss** [comment]
AFAIR we create all resources in a temporary namespace and then just remove that namespace after the test. So a `kubectl delete ns <temp-namespace>` should be enough. (@navidshaikh please me correct me when I'm wrong)

Or are you talking about cluster-wide resources ?

**Comment by MIBc** [comment]
I try delete ns. But `clusterrole` and `clusterrolebinding` still left.

**Comment by navidshaikh** [comment]
That's correct, though there are multiple test namespaces kne2etests[0-9], and the SA, ClusterRole and ClusterRoleBindings are introduced recently. We do need tear down functionality.

**Comment by rhuss** [comment]
correct, ClusterRole and ClusterRoleBindings are cluster-wide resources which need to be cleaned up seperately. I wonder, whether those cluster-wide resources (if different) work nicely with parallel running tests ? Or ar their names also randomized (so that they don't interfer which each other) ?

An idea: We could use the suffix of the namespace under test for the cluster role names and then just delete all clusterroles with those prefix. This would be generic enough and doesn't need constant maintenance.

**Comment by maximilien** [comment]
I am also seeing this too consistently.

Further (could be a different issue) the `kne2etestsX` namespaces from previous runs are not deleted so causes errors in subsequent runs of e2e. Unless I hear otherwise in next 12 hours I will open a separate issue. Seems consistent on my side.

**Comment by MIBc** [comment]
The danger is if there is a running e2e, which we can claim is not supported (e.g., running e2e multiple times at once). Thoughts?

-- It must fail . If a test is running, another test will meet `resource already exists` error.
