### ISSUE TITLE
Knative docs for `kn` CLI?

### ISSUE THREAD

**Issue by maximilien** [knative/client#623]
## In what area(s)?

Docs

> /kind doc

## Ask your question here:

Based on TOC discussion today (01/23) I am wondering how much docs from this repo we can submit to the official Knative docs repo? Perhaps the better approach is to submit use cases on how to use the `kn` client? For instance, I could submit my [knfun](https://github.com/maximilien/knfun) workflow? Or should we submit simpler examples or both?

NOTE: I could open this issue on the docs side, however, I think the message today was that the docs team needs help and the agreement after today’s TOC call is to summon each sub-team to help out the docs team. So essentially this issue is to discuss what is needed and we can agree on what to submit and do it and help.

Thoughts?

CC: @mattmoor @samodell

**Comment by samodell** [comment]
Hey @maximilien ! The goal is to have the main documentation for `kn` to live in the Docs repo eventually. Some work is in progress to make that a reality -- we're tracking that in this project here: 
https://github.com/knative/docs/projects/23

@abrennan89  and @rhuss  have been collaborating on that; if you're interested, I'm sure they'd be happy to have additional hands working on those docs.

For the `knfun` docs you linked, I'd love to see us link out to that repo from our community samples page: https://knative.dev/community/samples/index.html

There isn't a section there yet for `kn`-related things yet, but we can add one! And since those aren't quite code samples in the traditional sense, maybe we should add a section for demos and consider renaming that page.

**Comment by samodell** [comment]
And thanks for kicking off this discussion; I appreciate your interest in helping out!

**Comment by maximilien** [comment]
Cool @samodell. Happy to help. You can assign me anything related to `kn` plugins and creation parameters to start. I'll poke around the backlog today and next week and self-assign what I think I can help with.

**Comment by maximilien** [comment]
OK just sent a [PR #2132](https://github.com/knative/docs/pull/2132) to add [knfun](https://github.com/maximilien/knfun) to a new client samples section.

**Comment by maximilien** [comment]
Closing here since we have other issues being tracked for this. See @samodell comment ^^^
