### ISSUE TITLE
Broken link `kn in a Tekton Task`

### ISSUE THREAD

**Issue by pierDipi** [knative/client#933]
### Bug report

The link in the `README.md` at the following line returns `404`:

> An easy integration of Knative into Tekton Pipelines by using `kn in a Tekton Task`.

### Expected behavior

See kn in a Tekton Task documentation.

#### Additional context

Correct link: https://github.com/tektoncd/catalog/tree/master/task/kn

**Comment by navidshaikh** [comment]
Thanks @pierDipi! Looks like there was a recent [re-org](https://github.com/tektoncd/catalog/commit/28a08e2e411c88ee20b2b600f5eb5ae893cf39c1) of the tasks in catalog.

**Comment by pierDipi** [comment]
Yes, exactly.
Also, this repository has many markdown files with many links, it might be worth adding a non-blocking pre-submit check just like the `pull-knative-docs-markdown-link-check` that we have in `knative/docs` so that we can check these links. What do you think?

**Comment by navidshaikh** [comment]
@pierDipi :

markdown link check is enabled by default in the tests
see https://github.com/knative/test-infra/blob/master/scripts/presubmit-tests.sh#L24

and

[README](https://github.com/knative/test-infra/tree/master/scripts) excerpts:
```
DISABLE_MD_LINK_CHECK: Disable checking links in markdown files, defaults to 0 (false).
```

It didnt catch as README wasnt part of any PR raised lately (since change landed in catalog causing link to break). 
See it in action here https://github.com/knative/client/pull/934 ([logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/934/pull-knative-client-build-tests/1283379411067867138#1:build-log.txt%3A108))

**Comment by pierDipi** [comment]
Oh, TIL :smile: Thank you!
